### ISSUE TITLE
Change Project enums to dynamic collection of sorts

### ISSUE THREAD

**Issue by Termiux** [Termiux/CO-Docs-Admin#19]
There are several enumerations in the DocumentTypes file (CollectionTypes class) this needs to be renamed. 

Also we need to change the way the Project enumeration is handled since new projects are added without notice and the application breaks if the item didn't previously existed.

Right now trying to add CO 17922 breaks the app by having Project: "Premium Assistance Migration"

Log is below:

`2015-03-23 14:13:49,019 [5] ERROR CO_Admin.NewCO [(null)] - System.ArgumentException: Requested value 'Premium_Assistance_Migration' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at CO_Admin.Utilities.ToPwbProjectEnum(String value, Boolean ignoreCase) in C:\Users\user\Documents\GitHub\CO-Docs-Admin\CO Admin\CO Admin\Utilities.cs:line 300
   at CO_Admin.LoadChangeOrder.GetUpdatedChangeOrder() in C:\Users\user\Documents\GitHub\CO-Docs-Admin\CO Admin\CO Admin\LoadChangeOrder.cs:line 298
   at CO_Admin.ChangeOrder.UpdateChangeOrder(ChangeOrder changeOrder) in C:\Users\user\Documents\GitHub\CO-Docs-Admin\CO Admin\CO Admin\ChangeOrder.cs:line 240
   at CO_Admin.ChangeOrder..ctor(Int32 id, Boolean UpdateNow) in C:\Users\user\Documents\GitHub\CO-Docs-Admin\CO Admin\CO Admin\ChangeOrder.cs:line 53
   at CO_Admin.NewCO.backgroundWorker1_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\user\Documents\GitHub\CO-Docs-Admin\CO Admin\CO Admin\NewCO.cs:line 68`

**Comment by Termiux** [comment]
I suggest the creation of a List<string> that we have saved. This could be available via the preferences windows. Then if upon execution the program detected a string not in ourt List<string> then we could ask the user if they want to add it. This should probably be implemented for other ChangeOrder props as well

**Comment by Termiux** [comment]
Commit f4c424cf31c5cd4bc31e15859905c84cfba98f87 fixes #19
